name: jupyter_notebook
channels:
  - default
  - conda-forge
dependencies:
  - xeus-cling=0.12.1
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - notebook
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - pandas
  - matplotlib
  - pip:
    - quantecon
    - jupyter-book>=0.7.0b
